apiVersion: v1
kind: ConfigMap
metadata:
  name: bt-java-config
  namespace: your-namespace
data:
  # Bağlantı ve Yetki
  BEYONDTRUST_ENABLED: "true"
  BEYONDTRUST_API_URL: "https://bt-secrets-cache.turkcell.com.tr:1858"
  BEYONDTRUST_API_KEY: "b26a593fdf632aa951d69004f8531d99b5bc53c06c83607ef9d09f711d55a9221890a10cce3ad17af906f389424a6a07028be31fcabf4d1a00dfa21fef72f2f4; runas=enes;"

  # SSL ve Refresh Ayarları
  BEYONDTRUST_IGNORE_SSL_ERRORS: "true"
  BT_REFRESH_TIME: "60"

  # Hangi veriler çekilecek?
  BEYONDTRUST_MANAGED_ACCOUNTS: "dnsname (Db Instance: dbname, Port:1521).MA_EMPTYDB;EC2AMAZ-D6OKDG1.deneme"
  BEYONDTRUST_SECRET_SAFE_PATHS: "ENES_SC_DEMO_DEV,ENES_SC_DEMO_TEST"
  BEYONDTRUST_ALL_MANAGED_ACCOUNTS_ENABLED: "false"