apiVersion: v1
kind: ConfigMap
metadata:
  name: bt-dotnet-config
  namespace: enes-bt-cache
data:
  # Bağlantı ve Yetki
  BT_EXAMPLE_SAFE_USERNAME: "bt.safe.ENES_SC_DEMO_DEV.secret1.username"
  BT_EXAMPLE_SAFE_PASSWORD: "bt.safe.ENES_SC_DEMO_DEV.secret1.password"
  BT_EXAMPLE_ACCOUNT: "bt.acc.EC2AMAZ-D6OKDG1.deneme"
  BEYONDTRUST_ENABLED: "true"
  BEYONDTRUST_API_URL: "https://pam.quasys.com.tr/BeyondTrust/api/public/v3"
  BEYONDTRUST_API_KEY: "b26a593fdf632aa951d69004f8531d99b5bc53c06c83607ef9d09f711d55a9221890a10cce3ad17af906f389424a6a07028be31fcabf4d1a00dfa21fef72f2f4; runas=enes;"

  # SSL ve Refresh Ayarları
  BEYONDTRUST_IGNORE_SSL_ERRORS: "false"
  BT_REFRESH_TIME: "20"

  # Hangi veriler çekilecek?
  BEYONDTRUST_MANAGED_ACCOUNTS: "dnsname (Db Instance: dbname, Port:1521).MA_EMPTYDB;EC2AMAZ-D6OKDG1.deneme"
  BEYONDTRUST_SECRET_SAFE_PATHS: "ENES_SC_DEMO_DEV,ENES_SC_DEMO_TEST"
  BEYONDTRUST_ALL_MANAGED_ACCOUNTS_ENABLED: "false"
  BEYONDTRUST_CERTIFICATE_CONTENT: |-
    -----BEGIN CERTIFICATE-----
    MIIGejCCBWKgAwIBAgIQCxP8yr431fBRTbEeSyINlzANBgkqhkiG9w0BAQsFADBg
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMR8wHQYDVQQDExZHZW9UcnVzdCBUTFMgUlNBIENBIEcx
    MB4XDTI1MDgwMTAwMDAwMFoXDTI2MDkwMTIzNTk1OVowGjEYMBYGA1UEAwwPKi5x
    dWFzeXMuY29tLnRyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4BWo
    OI6cHZgV3pyvE8upY7Q7QoaIPHBVrdF6osShvYvcFAnstdHVJI/mFYak1JcEcPoA
    g4RQImh4S/92K184+WPmJbpbAEQqcQv+r/h64dVWQ2Nk1TxgzrBT6o8lYz2Ai28h
    68qpAyJNFD/f1FS6k7gsw7kGfAv0xKQrYAKq40r6zQ2QqlZ+Jmx19gvelvhNPBs+
    HTtvXT6cW11U02CsWTaosMZHPJhRk0Q08nljV3q7ju/Aexaw+cKAWRkQiTkVNiWO
    AAutpUKL3rpr2RTkP6EgAUZWKe1d/fWiPEfxKvfB85zKAYZdCGxno33i1ckgxDZD
    4ZivjrX5nfsQFvN60QIDAQABo4IDdDCCA3AwHwYDVR0jBBgwFoAUlE/UXYvkpOKm
    gP792PkA76O+AlcwHQYDVR0OBBYEFALcy71u0QtGmOEV06D7RyeAvQHqMHYGA1Ud
    EQRvMG2CDyoucXVhc3lzLmNvbS50coIMcXVhc3lzZHguY29tghB3d3cucXVhc3lz
    ZHguY29tgglxdWFzeXMuYXqCDXd3dy5xdWFzeXMuYXqCEXd3dy5xdWFzeXMuY29t
    LnRygg1xdWFzeXMuY29tLnRyMD4GA1UdIAQ3MDUwMwYGZ4EMAQIBMCkwJwYIKwYB
    BQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMC
    BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD8GA1UdHwQ4MDYwNKAy
    oDCGLmh0dHA6Ly9jZHAuZ2VvdHJ1c3QuY29tL0dlb1RydXN0VExTUlNBQ0FHMS5j
    cmwwdgYIKwYBBQUHAQEEajBoMCYGCCsGAQUFBzABhhpodHRwOi8vc3RhdHVzLmdl
    b3RydXN0LmNvbTA+BggrBgEFBQcwAoYyaHR0cDovL2NhY2VydHMuZ2VvdHJ1c3Qu
    Y29tL0dlb1RydXN0VExTUlNBQ0FHMS5jcnQwDAYDVR0TAQH/BAIwADCCAX4GCisG
    AQQB1nkCBAIEggFuBIIBagFoAHcA1219ENGn9XfCx+lf1wC/+YLJM1pl4dCzAXMX
    wMjFaXcAAAGYZUoDfQAABAMASDBGAiEAiO1MUH4OTH/+JDoK1bnKoKgFslozb3kb
    ZEQVwUpqlUQCIQD18oLagPjqQdig+8fzNTYrj3sXxVJrZmzj4yTVKFm4hQB2AMIx
    fldFGaNF7n843rKQQevHwiFaIr9/1bWtdprZDlLNAAABmGVKA+AAAAQDAEcwRQIg
    Z69/Wd9T7LP6bigvBTxdrRgTZLtLL/huc0P4sk/OvtQCIQD/CG8LIK1Mq6eEBFhS
    KU31XbEE18iqhy4xSyGEHcxd4QB1AJROQ4f67MHvgfMZJCaoGGUBx9NfOAIBP3Jn
    fVU3LhnYAAABmGVKA80AAAQDAEYwRAIgBcLbTxIyOGhBAMZkToCZ47QucIVoCjUG
    FCH9p7N0kysCIEbKcLBXPbxk24loPqcHP1dvIjWOD1jNXdud0fefwvhDMA0GCSqG
    SIb3DQEBCwUAA4IBAQBzCRwS1aMZchuJuJ4ybNzSpPCtYVeZGQY+R8QEohojl97Y
    4zKSk8My7dNu0Z4x0VVHIRZ6Cw2jmvVy9JgwfNlx643E0BJUeWjOm95DcD9oCo9o
    YIm/eEqAW8k7QonwMTp5QWV/fRzEvkqATnwGiKaXtYzuhHT3biLtq28fp8Bucwai
    NOK3y2332ZOkBzEbvvlkOE/H56b2tagGM0JTaLGo2Y/osBVJOqOdGvlv/4BAzaFr
    Wjj24i1gAJodXGhRCcwIT2q7k3iTVnZIs6uPM38iHTWbzcqIUB1TZ3OvhbSivfYu
    E4jfa+lVJQnYxL9Yu+tLrzlhn6EpzrrP6+p8ewA6
    -----END CERTIFICATE-----